Development (Needs testing)
ConcealNetwork/conceal-core pull request #311
Opened 2022-10-12 17:07 UTC by cartoon-face

*  implement `isSynchronized` query in NodeRPC
* `try` guard a mined block finding txs in the pool
* if another block is received, we shouldn't take them txs from the pool
* updates cors implementation
* Works on my machine

2022-10-15 17:24 UTC, AxVultis requested changes
It will need more testing after the changes. Thanks!

2022-10-15 17:24 UTC, AxVultis commented on src/NodeRpcProxy/NodeRpcProxy.cpp
> +  syncStatus = getPeerCount() > 0 && m_nodeHeight + 1 >= getLastKnownBlockHeight();
```suggestion
  syncStatus = getPeerCount() > 0 && getLastLocalBlockHeight() >= getLastKnownBlockHeight();
```

2022-10-15 22:14 UTC, cartoon-face commented
> It will need more testing after the changes. Thanks!

Changes have been, ready for testing when ready. More than welcome! 🚀

2022-11-18 10:31 UTC, AxVultis approved these changes
Looks good. Thanks!

2022-11-18 10:32 UTC, merged